### ISSUE TITLE
Boost context checks are broken with Boost 1.58.0

### ISSUE THREAD

**Issue by nlyan** [tsuna/boost.m4#84]
PowerDNS recently had to stop using the BOOST_CONTEXT macro because the current test includes the Boost context 'all.hpp' header, which, in Boost 1.58.0, brings in a broken 'execution_context.hpp' header. This code depends on C++11, resulting in failure under some build configurations.

The context library test should reduce it's header check to just the 'fcontext.hpp' header file, which is all the current tests depend upon.

Related bug reports:

https://github.com/PowerDNS/pdns/issues/3536

https://svn.boost.org/trac/boost/ticket/11223

**Comment by rkennedy** [comment]
In Boost 1.61, the `fcontext_t` type was removed from the public interface. It now lives in the `detail` namespace, and the corresponding header has moved, too.
